spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ssyx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
